[2024-12-21T14:23:25.456+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-21T14:23:25.506+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.Process_Bronze_to_Silver manual__2024-12-21T14:23:15.613039+00:00 [queued]>
[2024-12-21T14:23:25.518+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.Process_Bronze_to_Silver manual__2024-12-21T14:23:15.613039+00:00 [queued]>
[2024-12-21T14:23:25.519+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-21T14:23:25.688+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Process_Bronze_to_Silver> on 2024-12-21 14:23:15.613039+00:00
[2024-12-21T14:23:25.696+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=103) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-21T14:23:25.698+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2024-12-21T14:23:25.699+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline_dag', 'Process_Bronze_to_Silver', 'manual__2024-12-21T14:23:15.613039+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmplwgl3s3c']
[2024-12-21T14:23:25.700+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask Process_Bronze_to_Silver
[2024-12-21T14:23:25.758+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline_dag.Process_Bronze_to_Silver manual__2024-12-21T14:23:15.613039+00:00 [running]> on host 8bf0510c01ee
[2024-12-21T14:23:25.860+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Contato' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='Process_Bronze_to_Silver' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T14:23:15.613039+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-21T14:23:15.613039+00:00'
[2024-12-21T14:23:25.863+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-21T14:23:25.863+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-21T14:23:25.864+0000] {logging_mixin.py:190} INFO - Current task name:Process_Bronze_to_Silver state:running start_date:2024-12-21 14:23:25.507335+00:00
[2024-12-21T14:23:25.864+0000] {logging_mixin.py:190} INFO - Dag name:pipeline_dag and current dag run status:running
[2024-12-21T14:23:25.865+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-21T14:23:25.866+0000] {logging_mixin.py:190} INFO - initializing data extraction from Bronze folder
[2024-12-21T14:23:25.873+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 32, in process_bronze_to_silver
    df = pd.read_parquet('')
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''
[2024-12-21T14:23:25.888+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-21T14:23:25.889+0000] {logging_mixin.py:190} INFO - Task start:2024-12-21 14:23:25.507335+00:00 end:2024-12-21 14:23:25.888195+00:00 duration:0.38086
[2024-12-21T14:23:25.890+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): Process_Bronze_to_Silver> dag:<DAG: pipeline_dag> dagrun:<DagRun pipeline_dag @ 2024-12-21 14:23:15.613039+00:00: manual__2024-12-21T14:23:15.613039+00:00, state:running, queued_at: 2024-12-21 14:23:15.646215+00:00. externally triggered: True>
[2024-12-21T14:23:25.890+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: ''
[2024-12-21T14:23:25.891+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline_dag, task_id=Process_Bronze_to_Silver, run_id=manual__2024-12-21T14:23:15.613039+00:00, execution_date=20241221T142315, start_date=20241221T142325, end_date=20241221T142325
[2024-12-21T14:23:25.910+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-21T14:23:25.910+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 60 for task Process_Bronze_to_Silver ([Errno 2] No such file or directory: ''; 105)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 32, in process_bronze_to_silver
    df = pd.read_parquet('')
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''
[2024-12-21T14:23:25.924+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-21T14:23:25.951+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-21T14:23:25.953+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
