[2024-12-21T14:05:40.423+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-21T14:05:40.448+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.Extractor_Loader manual__2024-12-21T14:05:29.613559+00:00 [queued]>
[2024-12-21T14:05:40.464+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.Extractor_Loader manual__2024-12-21T14:05:29.613559+00:00 [queued]>
[2024-12-21T14:05:40.464+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 6
[2024-12-21T14:05:40.656+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Extractor_Loader> on 2024-12-21 14:05:29.613559+00:00
[2024-12-21T14:05:40.665+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=208) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-21T14:05:40.668+0000] {standard_task_runner.py:72} INFO - Started process 210 to run task
[2024-12-21T14:05:40.669+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline_dag', 'Extractor_Loader', 'manual__2024-12-21T14:05:29.613559+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmph07uy_gb']
[2024-12-21T14:05:40.671+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask Extractor_Loader
[2024-12-21T14:05:40.739+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline_dag.Extractor_Loader manual__2024-12-21T14:05:29.613559+00:00 [running]> on host 8546faed72ad
[2024-12-21T14:05:40.863+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Contato' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='Extractor_Loader' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T14:05:29.613559+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-21T14:05:29.613559+00:00'
[2024-12-21T14:05:40.864+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-21T14:05:40.865+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-21T14:05:40.866+0000] {logging_mixin.py:190} INFO - Current task name:Extractor_Loader state:running start_date:2024-12-21 14:05:40.449558+00:00
[2024-12-21T14:05:40.866+0000] {logging_mixin.py:190} INFO - Dag name:pipeline_dag and current dag run status:running
[2024-12-21T14:05:40.866+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-21T14:05:40.867+0000] {logging_mixin.py:190} INFO - initializing data extraction from raw folder
[2024-12-21T14:05:41.044+0000] {logging_mixin.py:190} INFO - saving data into bronze layer
[2024-12-21T14:05:41.045+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 22, in upload_raw_data_to_bronze
    pq.Table.from_pandas(df),
    ^^^^^^^^
AttributeError: module 'pyarrow.parquet' has no attribute 'Table'
[2024-12-21T14:05:41.061+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-21T14:05:41.062+0000] {logging_mixin.py:190} INFO - Task start:2024-12-21 14:05:40.449558+00:00 end:2024-12-21 14:05:41.061085+00:00 duration:0.611527
[2024-12-21T14:05:41.063+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): Extractor_Loader> dag:<DAG: pipeline_dag> dagrun:<DagRun pipeline_dag @ 2024-12-21 14:05:29.613559+00:00: manual__2024-12-21T14:05:29.613559+00:00, state:running, queued_at: 2024-12-21 14:05:29.625880+00:00. externally triggered: True>
[2024-12-21T14:05:41.063+0000] {logging_mixin.py:190} INFO - Failure caused by module 'pyarrow.parquet' has no attribute 'Table'
[2024-12-21T14:05:41.064+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline_dag, task_id=Extractor_Loader, run_id=manual__2024-12-21T14:05:29.613559+00:00, execution_date=20241221T140529, start_date=20241221T140540, end_date=20241221T140541
[2024-12-21T14:05:41.083+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-21T14:05:41.084+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 37 for task Extractor_Loader (module 'pyarrow.parquet' has no attribute 'Table'; 210)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 22, in upload_raw_data_to_bronze
    pq.Table.from_pandas(df),
    ^^^^^^^^
AttributeError: module 'pyarrow.parquet' has no attribute 'Table'
[2024-12-21T14:05:41.105+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-21T14:05:41.130+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-21T14:05:41.132+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
