[2024-12-21T14:45:49.731+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-21T14:45:49.761+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.Process_Silver_to_Gold manual__2024-12-21T14:45:33.317526+00:00 [queued]>
[2024-12-21T14:45:49.777+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.Process_Silver_to_Gold manual__2024-12-21T14:45:33.317526+00:00 [queued]>
[2024-12-21T14:45:49.778+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-21T14:45:49.967+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Process_Silver_to_Gold> on 2024-12-21 14:45:33.317526+00:00
[2024-12-21T14:45:49.976+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=603) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-21T14:45:49.979+0000] {standard_task_runner.py:72} INFO - Started process 605 to run task
[2024-12-21T14:45:49.980+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline_dag', 'Process_Silver_to_Gold', 'manual__2024-12-21T14:45:33.317526+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpgg6j4lyq']
[2024-12-21T14:45:49.982+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask Process_Silver_to_Gold
[2024-12-21T14:45:50.048+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline_dag.Process_Silver_to_Gold manual__2024-12-21T14:45:33.317526+00:00 [running]> on host 8bf0510c01ee
[2024-12-21T14:45:50.183+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Contato' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='Process_Silver_to_Gold' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T14:45:33.317526+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-21T14:45:33.317526+00:00'
[2024-12-21T14:45:50.185+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-21T14:45:50.186+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-21T14:45:50.187+0000] {logging_mixin.py:190} INFO - Current task name:Process_Silver_to_Gold state:running start_date:2024-12-21 14:45:49.762734+00:00
[2024-12-21T14:45:50.187+0000] {logging_mixin.py:190} INFO - Dag name:pipeline_dag and current dag run status:running
[2024-12-21T14:45:50.188+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-21T14:45:50.189+0000] {logging_mixin.py:190} INFO - initializing data transformation from Silver folder
[2024-12-21T14:45:50.361+0000] {logging_mixin.py:190} INFO - creating age groups
[2024-12-21T14:45:50.363+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 65, in process_silver_to_gold
    df_age = df_2['age'].apply(
             ^^^^
NameError: name 'df_2' is not defined
[2024-12-21T14:45:50.379+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-21T14:45:50.379+0000] {logging_mixin.py:190} INFO - Task start:2024-12-21 14:45:49.762734+00:00 end:2024-12-21 14:45:50.378556+00:00 duration:0.615822
[2024-12-21T14:45:50.380+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): Process_Silver_to_Gold> dag:<DAG: pipeline_dag> dagrun:<DagRun pipeline_dag @ 2024-12-21 14:45:33.317526+00:00: manual__2024-12-21T14:45:33.317526+00:00, state:running, queued_at: 2024-12-21 14:45:33.331373+00:00. externally triggered: True>
[2024-12-21T14:45:50.380+0000] {logging_mixin.py:190} INFO - Failure caused by name 'df_2' is not defined
[2024-12-21T14:45:50.381+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=pipeline_dag, task_id=Process_Silver_to_Gold, run_id=manual__2024-12-21T14:45:33.317526+00:00, execution_date=20241221T144533, start_date=20241221T144549, end_date=20241221T144550
[2024-12-21T14:45:50.394+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-21T14:45:50.395+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 78 for task Process_Silver_to_Gold (name 'df_2' is not defined; 605)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 65, in process_silver_to_gold
    df_age = df_2['age'].apply(
             ^^^^
NameError: name 'df_2' is not defined
[2024-12-21T14:45:50.450+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-21T14:45:50.475+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-21T14:45:50.478+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
