[2024-12-21T14:12:59.437+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-21T14:12:59.605+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.Extractor_Loader manual__2024-12-21T14:12:53.144210+00:00 [queued]>
[2024-12-21T14:12:59.615+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.Extractor_Loader manual__2024-12-21T14:12:53.144210+00:00 [queued]>
[2024-12-21T14:12:59.615+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-21T14:12:59.633+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Extractor_Loader> on 2024-12-21 14:12:53.144210+00:00
[2024-12-21T14:12:59.642+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-21T14:12:59.644+0000] {standard_task_runner.py:72} INFO - Started process 82 to run task
[2024-12-21T14:12:59.645+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline_dag', 'Extractor_Loader', 'manual__2024-12-21T14:12:53.144210+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp5af_i6iq']
[2024-12-21T14:12:59.646+0000] {standard_task_runner.py:105} INFO - Job 52: Subtask Extractor_Loader
[2024-12-21T14:12:59.702+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline_dag.Extractor_Loader manual__2024-12-21T14:12:53.144210+00:00 [running]> on host aa34a79e7118
[2024-12-21T14:12:59.806+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Contato' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='Extractor_Loader' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T14:12:53.144210+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-21T14:12:53.144210+00:00'
[2024-12-21T14:12:59.808+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-21T14:12:59.808+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-21T14:12:59.809+0000] {logging_mixin.py:190} INFO - Current task name:Extractor_Loader state:running start_date:2024-12-21 14:12:59.605842+00:00
[2024-12-21T14:12:59.809+0000] {logging_mixin.py:190} INFO - Dag name:pipeline_dag and current dag run status:running
[2024-12-21T14:12:59.810+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-21T14:12:59.810+0000] {logging_mixin.py:190} INFO - initializing data extraction from raw folder
[2024-12-21T14:12:59.960+0000] {logging_mixin.py:190} INFO - saving data into bronze layer
[2024-12-21T14:13:00.021+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 21, in upload_raw_data_to_bronze
    pq.write_to_dataset(
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/parquet/core.py", line 2172, in write_to_dataset
    ds.write_dataset(
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/dataset.py", line 1030, in write_dataset
    _filesystemdataset_write(
  File "pyarrow/_dataset.pyx", line 4047, in pyarrow._dataset._filesystemdataset_write
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
PermissionError: [Errno 13] Cannot create directory '/Users'. Detail: [errno 13] Permission denied
[2024-12-21T14:13:00.037+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-21T14:13:00.038+0000] {logging_mixin.py:190} INFO - Task start:2024-12-21 14:12:59.605842+00:00 end:2024-12-21 14:13:00.036733+00:00 duration:0.430891
[2024-12-21T14:13:00.038+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): Extractor_Loader> dag:<DAG: pipeline_dag> dagrun:<DagRun pipeline_dag @ 2024-12-21 14:12:53.144210+00:00: manual__2024-12-21T14:12:53.144210+00:00, state:running, queued_at: 2024-12-21 14:12:53.172731+00:00. externally triggered: True>
[2024-12-21T14:13:00.039+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 13] Cannot create directory '/Users'. Detail: [errno 13] Permission denied
[2024-12-21T14:13:00.039+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline_dag, task_id=Extractor_Loader, run_id=manual__2024-12-21T14:12:53.144210+00:00, execution_date=20241221T141253, start_date=20241221T141259, end_date=20241221T141300
[2024-12-21T14:13:00.055+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-21T14:13:00.055+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 52 for task Extractor_Loader ([Errno 13] Cannot create directory '/Users'. Detail: [errno 13] Permission denied; 82)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 21, in upload_raw_data_to_bronze
    pq.write_to_dataset(
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/parquet/core.py", line 2172, in write_to_dataset
    ds.write_dataset(
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/dataset.py", line 1030, in write_dataset
    _filesystemdataset_write(
  File "pyarrow/_dataset.pyx", line 4047, in pyarrow._dataset._filesystemdataset_write
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
PermissionError: [Errno 13] Cannot create directory '/Users'. Detail: [errno 13] Permission denied
[2024-12-21T14:13:00.074+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-21T14:13:00.099+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-21T14:13:00.101+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
