[2024-12-21T14:08:19.361+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-21T14:08:19.383+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_dag.Extractor_Loader manual__2024-12-21T14:08:16.181229+00:00 [queued]>
[2024-12-21T14:08:19.396+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_dag.Extractor_Loader manual__2024-12-21T14:08:16.181229+00:00 [queued]>
[2024-12-21T14:08:19.396+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-21T14:08:19.553+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Extractor_Loader> on 2024-12-21 14:08:16.181229+00:00
[2024-12-21T14:08:19.560+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=71) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-21T14:08:19.563+0000] {standard_task_runner.py:72} INFO - Started process 73 to run task
[2024-12-21T14:08:19.563+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline_dag', 'Extractor_Loader', 'manual__2024-12-21T14:08:16.181229+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpt2lhb9l9']
[2024-12-21T14:08:19.565+0000] {standard_task_runner.py:105} INFO - Job 44: Subtask Extractor_Loader
[2024-12-21T14:08:19.633+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline_dag.Extractor_Loader manual__2024-12-21T14:08:16.181229+00:00 [running]> on host 8546faed72ad
[2024-12-21T14:08:19.747+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Contato' AIRFLOW_CTX_DAG_ID='pipeline_dag' AIRFLOW_CTX_TASK_ID='Extractor_Loader' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T14:08:16.181229+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-21T14:08:16.181229+00:00'
[2024-12-21T14:08:19.750+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-21T14:08:19.750+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-21T14:08:19.751+0000] {logging_mixin.py:190} INFO - Current task name:Extractor_Loader state:running start_date:2024-12-21 14:08:19.383836+00:00
[2024-12-21T14:08:19.751+0000] {logging_mixin.py:190} INFO - Dag name:pipeline_dag and current dag run status:running
[2024-12-21T14:08:19.752+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-21T14:08:19.753+0000] {logging_mixin.py:190} INFO - initializing data extraction from raw folder
[2024-12-21T14:08:19.988+0000] {logging_mixin.py:190} INFO - saving data into bronze layer
[2024-12-21T14:08:19.989+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 22, in upload_raw_data_to_bronze
    pyarrow.Table.from_pandas(df),
    ^^^^^^^
NameError: name 'pyarrow' is not defined
[2024-12-21T14:08:20.012+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-21T14:08:20.015+0000] {logging_mixin.py:190} INFO - Task start:2024-12-21 14:08:19.383836+00:00 end:2024-12-21 14:08:20.012127+00:00 duration:0.628291
[2024-12-21T14:08:20.016+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): Extractor_Loader> dag:<DAG: pipeline_dag> dagrun:<DagRun pipeline_dag @ 2024-12-21 14:08:16.181229+00:00: manual__2024-12-21T14:08:16.181229+00:00, state:running, queued_at: 2024-12-21 14:08:16.213176+00:00. externally triggered: True>
[2024-12-21T14:08:20.016+0000] {logging_mixin.py:190} INFO - Failure caused by name 'pyarrow' is not defined
[2024-12-21T14:08:20.017+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=pipeline_dag, task_id=Extractor_Loader, run_id=manual__2024-12-21T14:08:16.181229+00:00, execution_date=20241221T140816, start_date=20241221T140819, end_date=20241221T140820
[2024-12-21T14:08:20.042+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-21T14:08:20.043+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 44 for task Extractor_Loader (name 'pyarrow' is not defined; 73)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 22, in upload_raw_data_to_bronze
    pyarrow.Table.from_pandas(df),
    ^^^^^^^
NameError: name 'pyarrow' is not defined
[2024-12-21T14:08:20.075+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-21T14:08:20.107+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-21T14:08:20.109+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
